name: Deploy to Vercel

on:
  push:
    branches: [ main ]

jobs:
  check-config:
    runs-on: ubuntu-latest
    outputs:
      has-secrets: ${{ steps.check-secrets.outputs.has-secrets }}
    steps:
    - name: Check if secrets are configured
      id: check-secrets
      run: |
        if [[ -n "${{ secrets.VERCEL_TOKEN }}" && -n "${{ secrets.PROJECT_ID }}" && -n "${{ secrets.ORG_ID }}" ]]; then
          echo "has-secrets=true" >> $GITHUB_OUTPUT
        else
          echo "has-secrets=false" >> $GITHUB_OUTPUT
        fi

  deploy:
    needs: check-config
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Instruções para primeiro deploy
      if: needs.check-config.outputs.has-secrets == 'false'
      run: |
        echo "🚀 PRIMEIRO DEPLOY - Configuração necessária:"
        echo ""
        echo "1️⃣ Acesse https://vercel.com"
        echo "2️⃣ Faça login com sua conta GitHub"
        echo "3️⃣ Clique 'New Project'"
        echo "4️⃣ Selecione o repositório 'Precificacao-Info-Agil'"
        echo "5️⃣ Configure:"
        echo "   - Framework: Other"
        echo "   - Build Command: (deixe vazio)"
        echo "   - Output Directory: ./"
        echo "6️⃣ Clique 'Deploy'"
        echo ""
        echo "📋 Arquivo principal: saas_pricing_calculator_v3.html"
        echo "📖 Guia completo: Veja SETUP-VERCEL.md no repositório"
        echo ""
        echo "⚠️ Após o primeiro deploy, configure os secrets no GitHub para deploy automático"
        
    - name: Deploy automático
      if: needs.check-config.outputs.has-secrets == 'true'
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        vercel-args: '--prod'
